name: Setup Docker on VM

on:
  workflow_run:
<<<<<<< HEAD
    workflows: ["Terraform Workflow"] 
=======
    workflows: ["Terraform"]
>>>>>>> 779b959b419ee47a80837a116bfc4fb735f476f3
    types:
      - completed

jobs:
  setup-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
<<<<<<< HEAD
      
    - name: Install Docker on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.SSH_KEY }}") ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
         
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
=======

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install Docker on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        # Проверка наличия sudo
        if ! command -v sudo &> /dev/null
        then
            echo "sudo could not be found, please install it or use a user with sufficient privileges."
            exit 1
        fi

        # Проверка наличия curl
        if ! command -v curl &> /dev/null
        then
            echo "curl could not be found, installing it now."
            sudo apt-get update && sudo apt-get install -y curl
        fi

        # Обновление и установка Docker
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo mkdir -p /etc/apt/keyrings
>>>>>>> 779b959b419ee47a80837a116bfc4fb735f476f3
        sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
<<<<<<< HEAD
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo docker run --rm hello-world
        sudo docke stop hello-world
        EOF
        
=======
        $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        # Запуск тестового контейнера
        sudo docker run --rm hello-world
        EOF
>>>>>>> 779b959b419ee47a80837a116bfc4fb735f476f3
